In [20]:
import numpy as np

# Define your matrix as a 2D NumPy array
# matrix = np.array([[2, 3, 1],
# [4, 1, 7],
# [0, 5, 2]])

matrix = np.array([[6, 24, 1],
                   [13, 16, 10],
                   [20, 17, 15]])

def determinant_matrix(matrix):
    # Calculate the determinant using the formula
    det = (matrix[0, 0] * (matrix[1, 1] * matrix[2, 2] - matrix[1, 2] * matrix[2, 1]) -
           matrix[0, 1] * (matrix[1, 0] * matrix[2, 2] - matrix[1, 2] * matrix[2, 0]) +
           matrix[0, 2] * (matrix[1, 0] * matrix[2, 1] - matrix[1, 1] * matrix[2, 0]))

    return det

def inverse_matrix(matrix):
    # Use the np.linalg.inv() function to find the inverse
    inverse_matrix = np.linalg.inv(matrix)
    return inverse_matrix

# Print the determinant
print("Determinant of a matrix:\n", determinant_matrix(matrix))

# Print the inverse matrix
inv_matrix = inverse_matrix(matrix)
print("Inverse of a matrix:\n", inv_matrix)

Determinant of a matrix:
 441
Inverse of a matrix:
 [[ 0.15873016 -0.77777778  0.50793651]
 [ 0.01133787  0.15873016 -0.10657596]
 [-0.2244898   0.85714286 -0.48979592]]
