In [4]:
import numpy as np

# Define a function to convert a string to a list of numbers
def text_to_numbers(text):
    text = text.lower().replace(" ", "")
    text_to_num = []
    for c in text:
        loc = alpha.find(c)
        text_to_num.append(loc)
    return text_to_num

# Define a function to convert a list of numbers to a string
def numbers_to_text(numbers):
    return ''.join([chr(num + ord('a')) for num in numbers])

# Define a function for Hill Cipher encryption
def hill_cipher_encrypt(plaintext, key_matrix):
    plaintext = plaintext.lower().replace(" ", "")
    while len(plaintext) % 3 != 0:
        plaintext += 'X'  # Padding with 'X' if necessary

    plaintext_numbers = text_to_numbers(plaintext)
    print("Plain text in numbers: ", plaintext_numbers)
    encrypted_numbers = []

    for i in range(0, len(plaintext_numbers), 3):
        block = np.array(plaintext_numbers[i:i+3])
        encrypted_block = np.dot(block, key_matrix) % 26
        print(encrypted_block)
        encrypted_numbers.extend(encrypted_block)
        print(encrypted_numbers)

    return numbers_to_text(encrypted_numbers)

# Define the Hill Cipher key matrix (3x3 matrix)
key_matrix = np.array([[17, 17, 5],
                      [21, 18, 21],
                      [2, 2, 19]])

plaintext = "paymoremoney"
alpha = 'abcdefghijklmnopqrstuvwxyz'

text_to_num = text_to_numbers(plaintext)
print("Indexing of letters in message:\n")
print(text_to_num)

encrypted_text = hill_cipher_encrypt(plaintext, key_matrix)
print("Plain text: ", plaintext)
print("Encrypted:", encrypted_text.upper())


Indexing of letters in message:

[15, 0, 24, 12, 14, 17, 4, 12, 14, 13, 4, 24]
Plain text in numbers:  [15, 0, 24, 12, 14, 17, 4, 12, 14, 13, 4, 24]
[17 17 11]
[17, 17, 11]
[12 22  1]
[17, 17, 11, 12, 22, 1]
[10  0 18]
[17, 17, 11, 12, 22, 1, 10, 0, 18]
[15  3  7]
[17, 17, 11, 12, 22, 1, 10, 0, 18, 15, 3, 7]
Plain text:  paymoremoney
Encrypted: RRLMWBKASPDH
